version: '3.5'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:management
    ports:
    - 5672:5672
  flower:
    image: mher/flower
    ports:
    - 5555:5555
    command: ["flower", "--broker=amqp://rabbitmq:5672"]
    depends_on:
      - rabbitmq
    environment:
      - FLOWER_BROKER_API_URL=http://guest:guest@broker:15672/api/vhost
  newsletter_site:
    build:
      context: .
    command: sh -c "python3 manage.py wait_for_db && python3 manage.py migrate && python3 manage.py init_admin &&python3 manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    ports:
    - 8000:8000
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
      - rabbitmq
    image: expert-lamp_celery:latest
  celery:
    restart: always
    build:
      context: .
    command: sh -c "celery -A newsletter_site worker -l info"
    depends_on:
      - newsletter_site
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672



# TODO: Configure volumes
# TODO: Add command to create superuser