version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
    - 5432:5432
  rabbitmq:
    image: rabbitmq
    ports:
    - 5672:5672
  flower:
    image: mher/flower
    ports:
    - 5555:5555
    command: ["flower", "--broker=amqp://rabbitmq:5672"]
    depends_on:
      - rabbitmq