apiVersion: v1
kind: ConfigMap
metadata:
  name: expert-lamp-configuration
data:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
  POSTGRES_PASSWORD: postgres
  CELERY_BROKER_URL: "pyamqp://localhost:5672"
  EMAIL_HOST: smtp.gmail.com
  EMAIL_USE_TLS: True
  EMAIL_PORT: 587
  EMAIL_HOST_USER: ambitrafika2@gmail.com
  EMAIL_HOST_PASSWORD: mfjnmuhuietakwvo
  DEBUG: False
  ALLOWED_HOSTS: "localhost 127.0.0.1 0.0.0.0 [::1]"
  SECRET_KEY: django-insecure-dk@i5*bo=01u_ko_g5iw@v0i3$jtsxn_wj9tg0x69ed=sg81oz